spring:
    datasource:
        url: jdbc:h2:file:./data/h2db
        driverClassName: org.h2.Driver
        username: yks
        password:

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
  
server: 
    port: 9000